#%RAML 0.8
title: Give me an Idea
version: "1.0"
baseUri: "http://itsthisforthat.com/api.php"
protocols: [HTTP]
securitySchemes: 
    - 
        apiKey: 
            type: x-apiKey
            describedBy: 
                headers: 
                    Authorization: 
                        type: string
                        required: false
                        repeat: false
securedBy: 
    - 
        apiKey
/: 
    displayName: /
    uriParameters: 
        text: 
            type: string
            required: false
            repeat: false
    get: 
documentation: 
    - 
        title: API Description
        content: Randomly generates ideas for you!!
