#%RAML 0.8
title: OpenFoodFactsAPI
version: "1.0"
baseUri: "https://world.openfoodfacts.org/"
protocols: [HTTP]
securitySchemes: 
    - 
        apiKey: 
            type: x-apiKey
            describedBy: 
                headers: 
                    Authorization: 
                        type: string
                        required: false
                        repeat: false
securedBy: 
    - 
        apiKey
/language/{language}.json: 
    get: 
        baseUriParameters: 
            language: 
                type: string
                required: false
                repeat: false
/category/{category}.json: 
    get: 
        baseUriParameters: 
            category: 
                type: string
                required: false
                repeat: false
/packaging/{packaging}.json: 
    get: 
        baseUriParameters: 
            packaging: 
                type: string
                required: false
                repeat: false
