#%RAML 0.8
title: Game of Thrones Quotes
version: "1.0"
baseUri: "https://got-quotes.herokuapp.com/"
protocols: [HTTP]
securitySchemes: 
    - 
        apiKey: 
            type: x-apiKey
            describedBy: 
                headers: 
                    Authorization: 
                        type: string
                        required: false
                        repeat: false
securedBy: 
    - 
        apiKey
/quotes: 
    displayName: quotes
    get: 
        queryParameters: 
            char: 
                description: |
                    Character name in Game of Thrones
                    example character names are 
                    1.vars
                    2.brynden
                    3.cersei
                    4.hound
                    5.jaime
                    6.littlefinger
                    7.olenna
                    8.renly
                    9.tyrion
                    10.varys
                type: string
                required: false
                repeat: false
                default: ""
documentation: 
    - 
        title: API Description
        content: provides random quotes and also provide the quotes based on character name of Game of Thrones
