#%RAML 0.8
title: Flights API
version: "1.0"
baseUri: "http://api.travelpayouts.com/"
protocols: [HTTP]
securitySchemes: 
    - 
        apiKey: 
            type: x-apiKey
            describedBy: 
                headers: 
                    Authorization: 
                        type: string
                        required: false
                        repeat: false
securedBy: 
    - 
        apiKey
/data/airlines.json: 
    displayName: Airline data in json format
    description: Airline data in json format
    get: 
        queryParameters: 
            token: 
                type: string
                required: false
                repeat: false
/v1/prices/cheap: 
    displayName: Cheapest tickets
    description: Returns the cheapest non-stop tickets, as well as tickets with 1 or 2 stops, for the selected route with departure/return date filters.
    get: 
        queryParameters: 
            origin: 
                type: string
                required: false
                repeat: false
            destination: 
                description: ""
                type: string
                required: false
                repeat: false
            depart_date: 
                description: depart_date=2017-11
                type: string
                required: false
                repeat: false
            token: 
                description: ""
                type: string
                required: false
                repeat: false
            return_date: 
                description: "2017-12"
                type: string
                required: false
                repeat: false
/data/airports.json: 
    displayName: Airport data in json format
    description: Airport data in json format
    get: 
        queryParameters: 
            token: 
                type: string
                required: false
                repeat: false
/v1/city-directions: 
    displayName: The popular destinations
    description: |
        The popular destinations
    get: 
        queryParameters: 
            origin: 
                description: origin
                type: string
                required: false
                repeat: false
            currency: 
                description: usd
                type: string
                required: false
                repeat: false
            token: 
                description: ""
                type: string
                required: false
                repeat: false
                enum: [d19182f2887f12733cb5c5608a1f27d8]
                default: d19182f2887f12733cb5c5608a1f27d8
/data/countries.json: 
    displayName: Data of countries in json format
    description: Data of countries in json format
    get: 
        queryParameters: 
            token: 
                type: string
                required: false
                repeat: false
/data/cities.json: 
    displayName: City data in json format
    description: City data in json format
    get: 
        queryParameters: 
            token: 
                type: string
                required: false
                repeat: false
/data/routes.json: 
    displayName: data/routes.json
    description: Data on the routes in json format
    get: 
        queryParameters: 
            token: 
                type: string
                required: false
                repeat: false
/v2/prices/latest: 
    displayName: Flight price history
    description: Brings back the list of prices found by our users during the most recent 48 hours according to the filters used.
    get: 
        queryParameters: 
            beginning_of_period: 
                description: the beginning of the period, within which the dates of departure fall (in the YYYY-MM-DD format, for example, 2016-05-01). Must be specified if period_type is equal to month.
                type: string
                required: false
                repeat: false
            one_way: 
                description: rue - one way, false - back-to-back. The default value - false.
                type: string
                required: false
                repeat: false
            trip_class: 
                description: |
                     the flight class:
                    0 — Economy class (the default value);
                    1 — Business class;
                    2 — First
                type: string
                required: false
                repeat: false
            origin: 
                description: ""
                type: string
                required: false
                repeat: false
            limit: 
                description: the total number of records on a page. The default value - 30. The maximum value - 1000.
                type: string
                required: false
                repeat: false
            destination: 
                description: ""
                type: string
                required: false
                repeat: false
            currency: 
                type: string
                required: false
                repeat: false
            page: 
                description: a page number. The default value - 1
                type: string
                required: false
                repeat: false
            period_type: 
                description: |
                    the period for which the tickets have been found (the required parameter):
                    year — for the whole time;
                    month — for a month.
                type: string
                required: false
                repeat: false
            token: 
                type: string
                required: false
                repeat: false
                enum: [d19182f2887f12733cb5c5608a1f27d8]
                default: d19182f2887f12733cb5c56