#%RAML 0.8
title: JSON Placeholder API
version: "1.0"
baseUri: "http://jsonplaceholder.typicode.com/"
protocols: [HTTP]
securitySchemes: 
    - 
        apiKey: 
            type: x-apiKey
            describedBy: 
                headers: 
                    Authorization: 
                        type: string
                        required: false
                        repeat: false
securedBy: 
    - 
        apiKey
/posts: 
    displayName: posts
    get: 
