#%RAML 0.8
title: Indian Railway API
version: "1.0"
baseUri: "http://api.railwayapi.com/"
protocols: [HTTP]
securitySchemes: 
    - 
        apiKey: 
            type: x-apiKey
            describedBy: 
                headers: 
                    Authorization: 
                        type: string
                        required: false
                        repeat: false
securedBy: 
    - 
        apiKey
/pnr_status/pnr/{pnr no}/apikey/{apikey}/: 
    displayName: PNR Status
    uriParameters: 
        apikey: 
            type: string
            required: false
            repeat: false
            enum: ["1prbu0fq"]
            default: "1prbu0fq"
        pnr no: 
            type: string
            required: false
            repeat: false
    get: 
/check_seat/train/{train number}/source/{sourcecode}/dest/{destcode}/date/{doj in DD-MM-YYYY}/class/{class code}/quota/{quota code}/apikey/{apikey}/: 
    displayName: Seat Availability
    uriParameters: 
        apikey: 
            type: string
            required: false
            repeat: false
            enum: ["1prbu0fq"]
            default: "1prbu0fq"
        destcode: 
            type: string
            required: false
            repeat: false
        class code: 
            type: string
            required: false
            repeat: false
        doj in DD-MM-YYYY: 
            type: string
            required: false
            repeat: false
        quota code: 
            type: string
            required: false
            repeat: false
        train number: 
            type: string
            required: false
            repeat: false
        sourcecode: 
            type: string
            required: false
            repeat: false
    get: 
/name_to_code/station/{station name}/apikey/{apikey}/: 
    displayName: Station Name to Code
    uriParameters: 
        apikey: 
            type: string
            required: false
            repeat: false
            enum: ["1prbu0fq"]
            default: "1prbu0fq"
        station name: 
            type: string
            required: false
            repeat: false
    get: 
/route/train/{train number}/apikey/{apikey}/: 
    displayName: Train Route
    uriParameters: 
        apikey: 
            type: string
            required: false
            repeat: false
            enum: ["1prbu0fq"]
            default: "1prbu0fq"
        train number: 
            type: string
            required: false
            repeat: false
    get: 
/between/source/{sourcecode}/dest/{destinationcode}/date/{dd-mm}/apikey/{apikey}/: 
    displayName: Trains Between Stations
    uriParameters: 
        dd-mm: 
            description: date 
            type: string
            required: false
            repeat: false
        destinationcode: 
            type: string
            required: true
            repeat: false
        apikey: 
            type: string
            required: false
            repeat: false
            enum: ["1prbu0fq"]
            default: "1prbu0fq"
        sourcecode: 
            type: string
            required: false
            repeat: false
    get: 
