#%RAML 0.8
title: Thirukkural
version: "1.0"
baseUri: "http://getthirukural.appspot.com/api/2.0/kural"
protocols: [HTTP]
securitySchemes: 
    - 
        apiKey: 
            type: x-apiKey
            describedBy: 
                headers: 
                    Authorization: 
                        type: string
                        required: false
                        repeat: false
securedBy: 
    - 
        apiKey
/{from-to}: 
    displayName: Kurals
    description: |
        from
        Numeric from value. Must be between 1 and 1330. Value not greater than to value. Example: 1.
        Number
        to
        Numeric to value. Must be between 1 and 1330. Value not lesser than from value. Example: 1.
    uriParameters: 
        appid: 
            description: ""
            type: string
            required: false
            repeat: false
            enum: [x5mwe55oderut]
            default: x5mwe55oderut
        from-to: 
            description: |
                from
                Numeric from value. Must be between 1 and 1330. Value not greater than to value. Example: 1.
                Number
                to
                Numeric to value. Must be between 1 and 1330. Value not lesser than from value. Example: 1.
            type: string
            required: false
            repeat: false
    get: 
/{number}: 
    displayName: "{number}"
    description: number in the range of 1-1330
    uriParameters: 
        number: 
            description: number in the range 1 - 1330
            type: string
            required: false
            repeat: false
        appid: 
            type: string
            required: false
            repeat: false
            enum: [x5mwe55oderut]
            default: x5mwe55oderut
    get: 
