#%RAML 0.8
title: ChuckNorrisAPI
version: "1.0"
baseUri: "http://api.chucknorris.io/jokes"
protocols: [HTTPs]
securitySchemes: 
    - 
        apiKey: 
            type: x-apiKey
            describedBy: 
                headers: 
                    Authorization: 
                        type: string
                        required: false
                        repeat: false
securedBy: 
    - 
        apiKey
/random: 
    get: 
        description: "(Untitled)"
documentation: 
    - 
        title: API Description
        content: Chuck Norris facts are satirical factoids about martial artist and actor Chuck Norris that have become an Internet phenomenon and as a result have become widespread in popular culture. The 'facts' are normally absurd hyperbolic claims about Norris' toughness, attitude, virility, sophistication, and masculinity.
