#%RAML 0.8
title: Word finding API
version: "1.0"
baseUri: "https://api.datamuse.com/"
protocols: [HTTP]
securitySchemes: 
    - 
        apiKey: 
            type: x-apiKey
            describedBy: 
                headers: 
                    Authorization: 
                        type: string
                        required: false
                        repeat: false
securedBy: 
    - 
        apiKey
/sug: 
    displayName: suggestion
    uriParameters: 
        s: 
            description: suggestions for the user if they have typed in rawand so far
            type: string
            required: false
            repeat: false
    get: 
/words: 
    displayName: words
    description: "Applications use the API for a wide range of features, including autocomplete on text input fields, search relevancy ranking, assistive writing apps, word games, and more. The following examples illustrate the kinds of queries you can make:"
    get: 
        queryParameters: 
            rel_jjb: 
                description: adjectives that are often used to describe
                type: string
                required: false
                repeat: false
            rel_rhy: 
                description: words that rhyme with
                type: string
                required: false
                repeat: false
            rel_jja: 
                description: nouns that are often described by the adjective 
                type: string
                required: false
                repeat: false
            topics: 
                description: ""
                type: string
                required: false
                repeat: false
            lc: 
                description: |
                    words that often follow "drink" in a sentence, that start with the letter w
                    /words?lc=drink&sp=w*
                type: string
                required: false
                repeat: false
            sl: 
                description: sounds like
                type: string
                required: false
                repeat: false
            rel_trg: 
                description: words that are triggered by (strongly associated with) 
                type: string
                required: false
                repeat: false
            sp: 
                description: |
                    start with the letter b (sp=b*)
                    end with the letter a (sp=*a)
                    start with t, end in k, and have two letters in between(sp=t??k)
                type: string
                required: false
                repeat: false
            ml: 
                description: words with a meaning similar to 
                type: string
                required: false
                repeat: false
documentation: 
    - 
        title: API Description
        content: API is a word-finding query engine for developers. You can use it in your apps to find words that match a given set of constraints and that are likely in a given context. You can specify a wide variety of constraints on meaning, spelling, sound, and vocabulary in your queries, in any combination.
