#%RAML 0.8
title: RESTCountries
version: "1.0"
baseUri: "http://restcountries.eu/rest/v2"
protocols: [HTTP]
securitySchemes: 
    - 
        apiKey: 
            type: x-apiKey
            describedBy: 
                headers: 
                    Authorization: 
                        type: string
                        required: false
                        repeat: false
securedBy: 
    - 
        apiKey
/capital/{capital}: 
    displayName: /capital/{capital}
    description: Search by capital city
    uriParameters: 
        capital: 
            description: "Eg : capital/tallinn"
            type: string
            required: true
            repeat: false
    get: 
/all: 
    displayName: /all
    description: get all countries details
    get: 
/currency/{currency}: 
    displayName: /currency/{currency}
    description: Search by ISO 4217 currency code
    uriParameters: 
        currency: 
            description: "Eg : currency/cop"
            type: string
            required: true
            repeat: false
    get: 
/name/{name}: 
    displayName: /name/{name}
    description: Search by country name. It can be the native name or partial name
    uriParameters: 
        name: 
            description: "Eg : /name/united"
            type: string
            required: true
            repeat: false
    get: 
/lang/{et}: 
    displayName: /lang/{et}
    description: Search by ISO 639-1 language code.
    uriParameters: 
        et: 
            description: "Eg: lang/es"
            type: string
            required: true
            repeat: false
    get: 
/alpha/{code}: 
    displayName: /alpha/{code}
    description: Search by ISO 3166-1 2-letter or 3-letter country code
    uriParameters: 
        code: 
            description: "Eg : /alpha/col"
            type: string
            required: true
            repeat: false
    get: 
/region/{region}: 
    displayName: /region/{region}
    description: "Search by region: Africa, Americas, Asia, Europe, Oceania"
    uriParameters: 
        region: 
            description: "Eg: /region/europe"
            type: string
            required: true
            repeat: false
    get: 
documentation: 
    - 
        title: API Description
        content: |
            REST COUNTRIES
            Get information about countries via a RESTful API
