#%RAML 0.8
title: TrumpThoughts
version: "1.0"
baseUri: "https://api.whatdoestrumpthink.com/api/v1/quotes"
protocols: [HTTP]
securitySchemes: 
    - 
        apiKey: 
            type: x-apiKey
            describedBy: 
                headers: 
                    Authorization: 
                        type: string
                        required: false
                        repeat: false
securedBy: 
    - 
        apiKey
/personalized: 
    displayName: personalized
    description: This endpoint gets you a personalized  Trump quote based upon the input that you give it.
    uriParameters: 
        q: 
            type: string
            required: true
            repeat: false
    get: 
/random: 
    displayName: /random
    description: This endpoint gets you a random  Trump quote. The quote is just a generic quote; it’s not neccesarily about a specific person.
    get: