#%RAML 0.8
title: Geo Location API
version: "1.0"
baseUri: "http://photon.komoot.de/api"
protocols: [HTTP]
securitySchemes: 
    - 
        apiKey: 
            type: x-apiKey
            describedBy: 
                headers: 
                    Authorization: 
                        type: string
                        required: false
                        repeat: false
securedBy: 
    - 
        apiKey
/reverse: 
    displayName: Reverse geocoding
    description: Reverse geocoding
    uriParameters: 
        lon: 
            description: long
            type: string
            required: false
            repeat: false
        lat: 
            description: lat
            type: string
            required: false
            repeat: false
    get: 
/: 
    displayName: /
    description: Search
    uriParameters: 
        q: 
            description: q=chennai
            type: string
            required: false
            repeat: false
        limit: 
            description: limit number of results
            type: string
            required: false
            repeat: false
        lon: 
            description: long
            type: string
            required: false
            repeat: false
        lat: 
            description: Search, with priority to a geo position  ex lat
            type: string
            required: false
            repeat: false
    get: 
documentation: 
    - 
        title: API Description
        content: OpenStreetProject made by Komoot that lets users to geographically locate the places they enter on the Photon platform. The Photon API lets developers to integrate this feature into their applications for use. The API uses GeoJSON format, and is free for use.
