#%RAML 0.8
title: NewsAPI
version: "1.0"
baseUri: "http://newsapi.org/v1"
protocols: [HTTP]
securitySchemes: 
    - 
        apiKey: 
            type: x-apiKey
            describedBy: 
                headers: 
                    Authorization: 
                        type: string
                        required: false
                        repeat: false
securedBy: 
    - 
        apiKey
/sources: 
    displayName: getBySource
    get: 
        queryParameters: 
            country: 
                description: |
                    The 2-letter ISO 3166-1 code of the country you would like to get sources for.
                    Possible options: au, de, gb, in, it, us.
                    Default: empty (all sources returned)
                type: string
                required: false
                repeat: false
            language: 
                description: |
                    The 2-letter ISO-639-1 code of the language you would like to get sources for.
                    Possible options: en, de, fr.
                    Default: empty (all sources returned)
                type: string
                required: false
                repeat: false
            category: 
                description: |
                    The category you would like to get sources for.
                    Possible options: business, entertainment, gaming, general, music, politics, science-and-nature, sport, technology.
                    Default: empty (all sources returned)
                type: string
                required: false
                repeat: false
        protocols: [HTTP]
/articles: 
    displayName: getByArticles
    get: 
        queryParameters: 
            sortBy: 
                description: "Specify which type of list you want. The possible options are top, latest and popular. Note: not all options are available for all sources. Default: top."
                type: string
                required: false
                repeat: false
            source: 
                description: The identifer for the news source or blog you want headlines from. Use the /sources endpoint to locate this or use the sources index.
                type: string
                required: true
                repeat: false
        protocols: [HTTP]
documentation: 
    - 
        title: API Description
        content: |
            News API is a simple and easy-to-use API that returns JSON metadata for the headlines currently published on a range of news sources and blogs (70 and counting so far).
            
            Use it to display live news headlines and images in your app or on your site!
    - 
        title: API Description
        content: |
            News API is a simple and easy-to-use API that returns JSON metadata for the headlines currently published on a range of news sources and blogs (70 and counting so far).
            
            Use it to display live news headlines and images in your app or on your site!
