#%RAML 0.8
title: PixabayAPI
version: "1.0"
baseUri: "https://pixabay.com/"
protocols: [HTTP]
securitySchemes: 
    - 
        apiKey: 
            type: x-apiKey
            describedBy: 
                headers: 
                    Authorization: 
                        type: string
                        required: false
                        repeat: false
securedBy: 
    - 
        apiKey
/api: 
    displayName: /api
    get: 
        queryParameters: 
            per_page: 
                description: |
                    Determine the number of results per page. 
                    Accepted values: 3 - 200 
                    Default: 20
                type: string
                required: false
                repeat: false
            pretty: 
                description: |
                    Indent JSON output. This option should not be used in production. 
                    Accepted values: "true", "false" 
                    Default: "false"
                type: string
                required: false
                repeat: false
            orientation: 
                description: |
                    Whether an image is wider than it is tall, or taller than it is wide. 
                    Accepted values: "all", "horizontal", "vertical" 
                    Default: "all"
                type: string
                required: false
                repeat: false
            safesearch: 
                description: |
                    A flag indicating that only images suitable for all ages should be returned. 
                    Accepted values: "true", "false" 
                    Default: "false"
                type: string
                required: false
                repeat: false
            editors_choice: 
                description: |
                    Select images that have received an Editor's Choice award. 
                    Accepted values: "true", "false" 
                    Default: "false"
                type: string
                required: false
                repeat: false
            response_group: 
                description: |
                    Choose between retrieving high resolution images and image details. When selecting details, you can access images up to a dimension of 960 x 720 px. 
                    Accepted values: "image_details", "high_resolution" (requires permission) 
                    Default: "image_details"
                type: string
                required: false
                repeat: false
            q: 
                description: |
                    A URL encoded search term. If omitted, all images are returned. This value may not exceed 100 characters. 
                    Example: "yellow+flower"
                type: string
                required: false
                repeat: false
            min_height: 
                description: |
                    Minimum image height. 
                    Default: "0"
                type: string
                required: false
                repeat: false
            callback: 
                description: JSONP callback function name
                type: string
                required: false
                repeat: false
            page: 
                description: |
                    Returned search results are paginated. Use this parameter to select the page number. 
                    Default: 1
                type: string
                required: false
                repeat: false
            id: 
                description: ID, hash ID, or a comma separated list of values for retrieving specific images. In a comma separated list, IDs and hash IDs cannot be used together.
                type: string
                required: false
                repeat: false
            category: 
                description: |
                    Filter results by category. 
                    Accepted values: fashion, nature, backgrounds, science, education, people, feelings, religion, health, places, animals, industry, food, computer, sports, transportation, travel, buildings, business, music
                type: string
                required: false
                repeat: false
            lang: 
                description: |
                    	Language code of the language to be searched in. 
                    Accepted values: cs, da, de, en, es, fr, id, it, hu, nl, no, pl, pt, ro, sk, fi, sv, tr, vi, th, bg, ru, el, ja, ko, zh 
                    Default: "en"
                type: string
                required: false
                repeat: false
            key: 
                description: mandate value
                type: string
                required: true
                repeat: false
                enum: ["5624369-0064f9dfbd5ea0db76e0676e3"]
                default: "5624369-0064f9dfbd5ea0db76e0676e3"
            order: 
                description: |
                    How the results should be ordered. 
                    Accepted values: "popular", "latest" 
                    Default: "popular"
                type: string
                required: false
                repeat: false
            min_width: 
                description: |
                    Minimum image width. 
                    Default: "0"
                type: string
                required: false
                repeat: false
            image_type: 
                description: |
                    Filter results by image type. 
                    Accepted values: "all", "photo", "illustration", "vector" 
                    Default: "all"
                type: string
                required: false
                repeat: false
