#%RAML 0.8
title: Duck Duck Go
version: "1.0"
baseUri: "https://api.duckduckgo.com/"
protocols: [HTTP]
securitySchemes: 
    - 
        apiKey: 
            type: x-apiKey
            describedBy: 
                headers: 
                    Authorization: 
                        type: string
                        required: false
                        repeat: false
securedBy: 
    - 
        apiKey
/: 
    displayName: Get instant answer
    uriParameters: 
        q: 
            description: example apply
            type: string
            required: false
            repeat: false
        pretty: 
            description: ""
            type: string
            required: false
            repeat: false
            enum: ["1"]
            default: "1"
        format: 
            description: json
            type: string
            required: false
            repeat: false
    get: 
documentation: 
    - 
        title: API Description
        content: Is a search engine which distinguishes itself by not tracking its users or generating results based on its usersâ€™ previous behavior. The  API provides free programmatic access to many of the search engineâ€™s instant answers, pulled from over 100 independent sources. Answers include things like topic summaries, categories, disambiguation, redirects, and def