#%RAML 0.8
title: Google Maps Time Zone API
version: "1.0"
baseUri: "https://maps.googleapis.com/maps/api"
protocols: [HTTP]
securitySchemes: 
    - 
        apiKey: 
            type: x-apiKey
            describedBy: 
                headers: 
                    Authorization: 
                        type: string
                        required: false
                        repeat: false
securedBy: 
    - 
        apiKey
/timezone/{outputFormat}: 
    displayName: Time Zone
    description: Time Zone API requests are constructed as a URL string. The API returns time zone data for a point on the earth, specified by a latitude/longitude pair. Note that time zone data may not be available for locations over water, such as oceans or seas.
    uriParameters: 
        outputFormat: 
            description: |
                outputFormat may be either of the following values:
                json (recommended), indicates output in JavaScript Object Notation (JSON); or
                xml, indicates output in XML, wrapped within a <TimeZoneResponse> node.
            type: string
            required: true
            repeat: false
            default: ""
    get: 
        queryParameters: 
            language: 
                description: "The language in which to return results. Seehttps://developers.google.com/maps/faq#languagesupport. Note that we often update supported languages so this list may not be exhaustive. Defaults to en."
                type: string
                required: false
                repeat: false
            location: 
                description: a comma-separated lat,lng tuple (eg. location=-33.86,151.20), representing the location to look up.
                type: string
                required: true
                repeat: false
            key: 
                description: This key identifies your application for purposes of quota management.
                type: string
                required: true
                repeat: false
                enum: [AIzaSyB33fOKGWYH2vNM34ProYx93jvpxivgiio]
                default: AIzaSyB33fOKGWYH2vNM34ProYx93jvpxivgiio
            timestamp: 
                description: specifies the desired time as seconds since midnight, January 1, 1970 UTC. The Google Maps Time Zone API uses the timestamp to determine whether or not Daylight Savings should be applied, based on the time zone of the location. Note that the API does not take historical time zones into account. That is, if you specify a past timestamp, the API does not take into account the possibility that the location was previously in a different time zone.
                type: string
                required: true
                repeat: false
        responses: 
            "200": 
                body: 
                    application/xml: 
                        schema: ""
                        example: |
                            <TimeZoneResponse>
                              <status>OK</status>
                              <raw_offset>-28800.0000000</raw_offset>
                              <dst_offset>0.0000000</dst_offset>
                              <time_zone_id>America/Los_Angeles</time_zone_id>
                              <time_zone_name>Pacific Standard Time</time_zone_name>
                            </TimeZoneResponse>
                    application/json: 
                        schema: ""
                        example: |
                            {
                               "dstOffset" : 0,
                               "rawOffset" : -28800,
                               "status" : "OK",
                               "timeZoneId" : "America/Los_Angeles",
                               "timeZoneName" : "Pacific Standard Time"
                            }
                                
documentation: 
    - 
        title: API Description
        content: The Google Maps Time Zone API provides time offset data for locations on the surface of the earth. You request the time zone information for a specific latitude/longitude pair and date. The API returns the name of that time zone, the time offset from UTC, and the daylight savings offset.
